### ISSUE TITLE
Scintilla.h is out of date and incompatible with x64 builds.

### ISSUE THREAD

**Issue by Kered13** [npp-plugins/plugintemplate#4]
See the current version of Scintilla.h used by NPP here:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/include/Scintilla.h

The difference I noticed was in `SCNotification`, where the current version has `Sci_Position position` while this template has `int position`. On x64 builds these types are not the same size, which causes runtime errors when reading the notification fields.

**Comment by donho** [comment]
https://github.com/npp-plugins/plugintemplate/commit/d2814d4bd9d96c475673e3a1902d318fb869059e
