### ISSUE TITLE
Update the plugin template to avoid throwing an exception from DllMain

### ISSUE THREAD

**Issue by mere-human** [npp-plugins/plugintemplate#5]
**Description:**
Plugin DLL should not throw from the DllMain() under any circumstances.
This crashes the host application during startup.
Prevent issues like this one: https://github.com/Hsilgos/nppsaveasadmin/issues/24

**Expected behavior:**
Add `try { } catch (...) { return FALSE: }` into `DllMain()`

**Comment by donho** [comment]
https://github.com/npp-plugins/plugintemplate/commit/bde87a13c94f3316026b131eee7063feca48817d
